title: Website
author: Advik Sirimarapu
email: asirimarapu@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Made by Advik Sirimarapu
# social links
instagram_username: advik_sp # DO NOT include the @ character, or else the build will fail!
github_username:  advik1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
